codecov:
  token: 85c13d8a-e9e1-49fd-97d4-7ba103f3e830
  notify:
    wait_for_ci: no
  require_ci_to_pass: no
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        removed_code_behavior: adjust_base
