name: Close stale issues and PRs

on:
  schedule:
  - cron: 42 4 * * 6

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v8
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: This issue will be closed in 90 days due to five years of inactivity unless the stale label or comment is removed.
        close-issue-message: This issue was closed because it has had no activity for five years.
        stale-pr-message: This pull request will be closed in 60 days due to a year of inactivity unless the stale label or comment is removed.
        close-pr-message: This pull request was closed because it has had no activity for the past year.
        days-before-issue-stale: 1826
        days-before-issue-close: 90
        days-before-pr-stale: 366
        days-before-pr-close: 60
        exempt-issue-labels:
        - Bug
        - 'Bug: needs more info'
        - 'Priority: high'
        - 'Priority: critical'
